# Generated by Django 5.0.4 on 2024-04-14 14:45

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Shiyan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lid", models.CharField(max_length=100)),
                ("uid", models.CharField(max_length=10)),
                ("pingyu", models.CharField(max_length=100)),
                ("datetime", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "实验",
                "verbose_name_plural": "实验",
            },
        ),
    ]
