# Generated by Django 5.0.4 on 2024-04-14 23:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shiyan", "0002_shiyan_file_shiyan_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="shiyan",
            name="chong",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shiyan",
            name="text",
            field=models.TextField(default=1, max_length=10000),
            preserve_default=False,
        ),
    ]
