# Generated by Django 5.0.4 on 2024-04-14 23:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shiyan", "0003_shiyan_chong_shiyan_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shiyan",
            name="score",
            field=models.CharField(max_length=100),
        ),
    ]
