# Generated by Django 5.0.4 on 2024-04-15 00:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shiyan", "0004_alter_shiyan_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="shiyan",
            name="url",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
